
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[176] =
    {   0,
       61,   61,   71,   69,   61,   65,   69,   68,   69,   69,
       50,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   69,
       61,    0,   64,   50,   67,    0,   50,   66,   63,   63,
       35,   63,   63,   63,   63,   63,   63,   12,   14,   11,
       63,   23,   36,   63,   63,   63,   16,   15,   63,   10,
       63,   63,   13,   63,   63,   63,   63,   63,   40,   63,
       34,   63,   63,   41,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   67,    3,   63,   63,    9,    6,   39,
       31,   63,    8,   30,   63,   18,   17,   63,    7,    2,

        5,   24,   63,   20,   63,   63,   63,   22,   63,   63,
       63,    4,    0,   51,    0,    0,    0,    0,    0,    0,
        0,   32,   21,   29,   33,   27,   62,   37,   38,   19,
       63,   63,   63,    0,    0,   60,    0,    0,    0,    0,
        0,    0,    0,   43,    0,   44,    0,    0,   48,   42,
       49,    1,   28,   63,   63,   55,    0,   56,    0,   52,
       54,   53,   47,    0,    0,   25,   26,   59,    0,    0,
       45,   46,   57,   58,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   10,    1,    1,
        1,    1,    1,    1,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   33,   34,   35,
       36,    1,   37,    1,    1,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   55,   56,   57,   58,   59,   33,   33,
       60,   61,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[62] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    1,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2
    } ;

static yyconst flex_int16_t yy_base[179] =
    {   0,
        0,    0,  351,  578,  344,  578,  325,  578,  319,  318,
       60,   61,   62,   63,   66,   76,   79,   81,   97,  108,
      118,  114,  112,  145,  144,  147,  171,  180,   85,  232,
      314,  276,  245,  227,    0,   95,  182,  578,  111,  148,
      123,  186,  199,  198,  183,  212,  214,  138,  210,  215,
      221,  247,  217,  244,  254,  263,  266,  280,  281,  291,
      295,  293,  298,  304,  308,  311,  310,  315,  329,  333,
      331,  345,  350,  356,  223,   89,   40,   61,   56,  137,
      221,  192,  220,    0,  338,  343,  365,  366,  370,  372,
      375,  376,  382,  389,  391,  392,  393,  402,  403,  405,

      407,  408,  409,  418,  421,  422,  420,  424,  425,  434,
      444,  437,  226,  483,  161,  224,  160,  429,  257,  158,
      320,  450,  453,  456,  457,  459,  469,  471,  472,  473,
      484,  486,  495,    0,  174,  165,  243,  256,  258,  351,
      156,  372,  143,  578,  114,  578,  401,  417,  578,  578,
      578,  483,  489,  498,  513,  578,  475,  578,  494,  136,
      578,  122,  578,   47,   43,  517,  524,  578,  476,  482,
      578,  578,  578,  578,  578,  573,   65,  575
    } ;

static yyconst flex_int16_t yy_def[179] =
    {   0,
      175,    1,  175,  175,  175,  175,  176,  175,  175,  175,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  175,
      175,  176,  176,  175,  178,  175,  177,  175,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  178,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,

      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  114,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  177,  177,  177,  177,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  177,  177,  175,  175,  175,
      175,  175,  175,  175,    0,  175,  175,  175
    } ;

static yyconst flex_int16_t yy_nxt[640] =
    {   0,
        4,    5,    6,    7,    4,    8,    9,   10,   11,    8,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       17,   22,   23,   24,   25,   26,   17,   27,   28,   29,
       17,   17,   17,   17,   17,   30,    4,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   17,   22,   23,
       24,   25,   26,   17,   27,   28,   29,   17,   17,   17,
       17,   36,   36,   36,   36,  115,   39,   36,   37,   38,
       38,   38,   38,   43,   40,   38,  116,   36,   44,  172,
       36,  117,   36,  171,   45,   38,   36,   41,   38,   42,
       38,   46,  115,   74,   38,   49,   36,   76,   36,   47,

       43,   40,   48,  116,   38,   44,   38,   51,  117,   36,
       50,   45,   36,   36,   41,   36,   42,   38,   46,   36,
       38,   38,   49,   38,   36,  114,   47,   38,   58,   48,
      162,   52,   38,   53,   51,   54,   61,   50,   59,   36,
       55,   56,   62,   60,  160,   36,   36,   38,   36,   36,
      163,  162,   57,   38,   38,   58,   38,   38,   52,   63,
       53,   85,   54,   61,  160,   59,  118,   55,   56,   62,
       60,   66,   36,  136,   64,   65,   67,   68,   57,   69,
       38,   36,  136,   36,   36,   70,   63,   36,   85,   38,
       37,   38,   38,  118,  150,   38,  146,  144,   66,   36,

       36,   64,   65,   67,   68,   71,   86,   38,   38,   72,
       73,   36,   70,   36,   89,   36,   36,  120,   36,   38,
       87,   38,   36,   38,   38,   88,   38,   91,  121,  119,
       38,  113,   71,   86,  113,   34,   72,   73,   75,   90,
       76,   89,   92,   77,  120,   36,   78,   87,   36,   33,
       79,  145,   88,   38,   91,   36,   38,   80,   95,   81,
       82,   83,  134,   38,   36,  119,   90,   36,  156,   92,
       77,  157,   38,   78,   93,   38,   94,   79,  145,   96,
       33,   36,   36,  158,   80,   95,   81,   82,   83,   38,
       38,   98,   36,  149,   36,  156,   36,   97,  157,   36,

       38,   93,   38,   94,   38,   36,   96,   38,   99,   36,
      158,   36,   36,   38,  101,   31,   36,   38,   98,   38,
       38,  105,  103,   97,   38,   35,  100,   34,  121,   33,
       36,  106,   36,  102,   36,   99,  104,   69,   38,   36,
       38,  101,   38,  107,   36,   31,   36,   38,  105,  103,
      175,   36,   38,  100,   38,  109,  151,   36,  106,   38,
      102,  112,  108,  104,   74,   38,   36,   36,  122,  110,
      107,   36,  111,   36,   38,   38,   36,   36,  175,   38,
      159,   38,  109,   36,   38,   38,  123,  175,  112,  108,
       36,   38,   36,   36,   36,  122,  110,  161,   38,  111,

       38,   38,   38,   36,   36,  124,   36,  159,   36,   36,
       36,   38,   38,  123,   38,  126,   38,   38,   38,   36,
      125,   36,   36,   36,  161,   36,   36,   38,  164,   38,
       38,   38,  124,   38,   38,   36,  127,  130,   36,  175,
      147,  175,  126,   38,  165,   36,   38,  125,  128,  129,
      148,   36,  131,   38,   36,  164,  133,   36,   36,   38,
       36,  132,   38,  127,  130,   38,   38,  147,   38,  175,
       36,  165,   36,   36,   36,  128,  129,  148,   38,  131,
       38,   38,   38,  133,   36,   36,  175,   36,  132,  135,
       36,  136,   38,   38,  137,   38,   36,  138,   38,   36,

      153,  139,  168,  173,   38,  169,  175,   38,  140,  174,
      141,  142,  143,  152,   36,  170,  175,  154,   36,  175,
      155,  137,   38,  166,  138,   36,   38,  153,  139,  168,
      173,  175,  169,   38,  175,  140,  174,  141,  142,  143,
      152,  175,  170,  175,  154,  175,  167,  155,  175,  175,
      166,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  167,   32,   32,   84,   84,    3,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,

      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175
    } ;

static yyconst flex_int16_t yy_chk[640] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   11,   12,   13,   14,   77,  177,   15,   11,   11,
       12,   13,   14,   14,   12,   15,   78,   16,   15,  165,
       17,   79,   18,  164,   15,   16,   29,   13,   17,   13,
       18,   16,   77,   29,   29,   18,   36,   76,   19,   16,

       14,   12,   16,   78,   36,   15,   19,   19,   79,   20,
       18,   15,   39,   23,   13,   22,   13,   20,   16,   21,
       39,   23,   18,   22,   41,   76,   16,   21,   22,   16,
      162,   20,   41,   20,   19,   20,   23,   18,   22,   48,
       21,   21,   23,   22,  160,   25,   24,   48,   26,   40,
      145,  143,   21,   25,   24,   22,   26,   40,   20,   24,
       20,   40,   20,   23,  141,   22,   80,   21,   21,   23,
       22,   26,   27,  136,   25,   25,   26,   26,   21,   27,
       27,   28,  135,   37,   45,   27,   24,   42,   40,   28,
       37,   37,   45,   80,  120,   42,  117,  115,   26,   44,

       43,   25,   25,   26,   26,   28,   42,   44,   43,   28,
       28,   49,   27,   46,   45,   47,   50,   82,   53,   49,
       43,   46,   51,   47,   50,   44,   53,   47,   83,   81,
       51,   75,   28,   42,  113,   34,   28,   28,   30,   46,
       30,   45,   51,   30,   82,   54,   30,   43,   52,   33,
       30,  116,   44,   54,   47,   55,   52,   30,   54,   30,
       30,   30,  113,   55,   56,  119,   46,   57,  137,   51,
       30,  138,   56,   30,   52,   57,   52,   30,  116,   55,
       32,   58,   59,  139,   30,   54,   30,   30,   30,   58,
       59,   59,   60,  119,   62,  137,   61,   56,  138,   63,

       60,   52,   62,   52,   61,   64,   55,   63,   61,   65,
      139,   67,   66,   64,   62,   31,   68,   65,   59,   67,
       66,   67,   65,   56,   68,   10,   61,    9,  121,    7,
       69,   67,   71,   64,   70,   61,   66,   69,   69,   85,
       71,   62,   70,   68,   86,    5,   72,   85,   67,   65,
        3,   73,   86,   61,   72,   72,  121,   74,   67,   73,
       64,   73,   70,   66,   74,   74,   87,   88,   86,   72,
       68,   89,   72,   90,   87,   88,   91,   92,    0,   89,
      140,   90,   72,   93,   91,   92,   87,    0,   73,   70,
       94,   93,   95,   96,   97,   86,   72,  142,   94,   72,

       95,   96,   97,   98,   99,   92,  100,  140,  101,  102,
      103,   98,   99,   87,  100,   98,  101,  102,  103,  104,
       95,  107,  105,  106,  142,  108,  109,  104,  147,  107,
      105,  106,   92,  108,  109,  110,  103,  107,  112,    0,
      118,    0,   98,  110,  148,  111,  112,   95,  105,  106,
      118,  122,  109,  111,  123,  147,  111,  124,  125,  122,
      126,  110,  123,  103,  107,  124,  125,  118,  126,    0,
      127,  148,  128,  129,  130,  105,  106,  118,  127,  109,
      128,  129,  130,  111,  152,  131,    0,  132,  110,  114,
      153,  114,  152,  131,  114,  132,  133,  114,  153,  154,

      132,  114,  157,  169,  133,  159,    0,  154,  114,  170,
      114,  114,  114,  131,  155,  159,    0,  133,  166,    0,
      133,  114,  155,  154,  114,  167,  166,  132,  114,  157,
      169,    0,  159,  167,    0,  114,  170,  114,  114,  114,
      131,    0,  159,    0,  133,    0,  155,  133,    0,    0,
      154,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  155,  176,  176,  178,  178,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,

      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "decode.lex"
#line 2 "decode.lex"
	#include "instr.h"
	#include "data.h"
	#include "interrupt.h"
	#define YY_INPUT(buf,result,max_size)	\
	{										\
		int len;							\
		strcpy(buf, instruction);			\
		len = strlen(buf);					\
		if(!strcmp(buf,"OVER\n"))			\
		{									\
 			result = YY_NULL;				\
		}									\
		else								\
		{									\
			result = len;					\
		}									\
	}
	char tempbuf[16];
	void get_lexdata(char buf1[],char buf2[]);
#line 679 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 25 "decode.lex"


#line 869 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 176 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 578 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 27 "decode.lex"
{ /*printf("START instruction found!! \n");*/return(START);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "decode.lex"
{ yylval.flag=0; yylval.flag2=0; return(MOV); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 29 "decode.lex"
{ yylval.flag=ADD; yylval.flag2=0; return(ARITH); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 30 "decode.lex"
{ yylval.flag=SUB; yylval.flag2=0; return(ARITH); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 31 "decode.lex"
{ yylval.flag=MUL; yylval.flag2=0; return(ARITH); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 32 "decode.lex"
{ yylval.flag=DIV; yylval.flag2=0; return(ARITH); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 33 "decode.lex"
{ yylval.flag=MOD; yylval.flag2=0; return(ARITH); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 34 "decode.lex"
{ yylval.flag=INR; yylval.flag2=0; return(ARITH); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 35 "decode.lex"
{ yylval.flag=DCR; yylval.flag2=0; return(ARITH); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 36 "decode.lex"
{ yylval.flag=LT; yylval.flag2=0; return(LOGIC); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 37 "decode.lex"
{ yylval.flag=GT; yylval.flag2=0; return(LOGIC); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 38 "decode.lex"
{ yylval.flag=EQ; yylval.flag2=0; return(LOGIC); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 39 "decode.lex"
{ yylval.flag=NE; yylval.flag2=0; return(LOGIC); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 40 "decode.lex"
{ yylval.flag=GE; yylval.flag2=0; return(LOGIC); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 41 "decode.lex"
{ yylval.flag=LE; yylval.flag2=0; return(LOGIC); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 42 "decode.lex"
{ yylval.flag=JZ; yylval.flag2=0; return(BRANCH); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 43 "decode.lex"
{ yylval.flag=JNZ; yylval.flag2=0; return(BRANCH); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 44 "decode.lex"
{ yylval.flag=JMP; yylval.flag2=0; return(BRANCH); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 45 "decode.lex"
{ yylval.flag=0; yylval.flag2=0; return(PUSH); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 46 "decode.lex"
{ yylval.flag=0; yylval.flag2=0; return(POP); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 47 "decode.lex"
{ yylval.flag=0; yylval.flag2=0; return(CALL); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 48 "decode.lex"
{ yylval.flag=0; yylval.flag2=0; return(RET); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 49 "decode.lex"
{ yylval.flag=0; yylval.flag2=0; return(IN); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 50 "decode.lex"
{ yylval.flag=0; yylval.flag2=0; return(OUT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 51 "decode.lex"
{ yylval.flag=0; yylval.flag2=0; return(STRCMP); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 52 "decode.lex"
{ yylval.flag=0; yylval.flag2=0; return(STRCPY); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 53 "decode.lex"
{ yylval.flag=0; yylval.flag2=0; return(LOAD); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 54 "decode.lex"
{ yylval.flag=0; yylval.flag2=0; return(STORE); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 55 "decode.lex"
{ printf("OVER!!!!!!!!\n");yylval.flag=0; yylval.flag2=0; return(HALT); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 56 "decode.lex"
{ yylval.flag=0; yylval.flag2=0; return(INT); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 57 "decode.lex"
{ yylval.flag=0; yylval.flag2=0; return(END); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 58 "decode.lex"
{ yylval.flag=0; yylval.flag2=0; return(BRKP); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 59 "decode.lex"
{ yylval.flag=0; yylval.flag2=0; return(IRET);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 60 "decode.lex"
{ yylval.flag=SP; yylval.flag2=0; return(0); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 61 "decode.lex"
{ yylval.flag=BP; yylval.flag2=0; return(0); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 62 "decode.lex"
{ /*printf("<ERROR:%d:> IP cannot be an arguement\n",getInteger(reg[IP_REG]));exit(0);*/
		  	yylval.flag=IP; yylval.flag2=0; return(0); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 64 "decode.lex"
{ yylval.flag=PTBR; yylval.flag2=0; return(0); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 65 "decode.lex"
{ yylval.flag=PTLR; yylval.flag2=0; return(0); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 66 "decode.lex"
{ yylval.flag=EFR; yylval.flag2=0; return(0); } 	
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 67 "decode.lex"
{ yylval.flag=REG; yylval.flag2=0; yytext++; return(atoi(yytext));	}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 68 "decode.lex"
{ yylval.flag=REG; yylval.flag2=0; yytext++; return(atoi(yytext) + T0); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 69 "decode.lex"
{ yylval.flag=MEM_SP; yylval.flag2=0; return(0); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 70 "decode.lex"
{ yylval.flag=MEM_BP; yylval.flag2=0; return(0); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 71 "decode.lex"
{ yylval.flag=MEM_IP; yylval.flag2=0; return(0); }		//error: Is this needed.
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 72 "decode.lex"
{ yylval.flag=MEM_PTBR; yylval.flag2=0; return(0); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 73 "decode.lex"
{ yylval.flag=MEM_PTLR; yylval.flag2=0; return(0); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 74 "decode.lex"
{ yylval.flag=MEM_EFR; yylval.flag2=0; return(0); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 75 "decode.lex"
{	
				yylval.flag=MEM_REG; yylval.flag2=0; 
				yytext[yyleng-1]='\0';
				yytext=yytext+2;
				return(atoi(yytext)); 
				}	
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 81 "decode.lex"
{
				yylval.flag=MEM_REG; yylval.flag2=0; 
				yytext[yyleng-1]='\0';
				yytext=yytext+2;
				return(atoi(yytext) + T0); 
				}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 87 "decode.lex"
{ yylval.flag=NUM; yylval.flag2=0; return(atoi(yytext)); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 88 "decode.lex"
{
				yylval.flag=MEM_DIR; yylval.flag2=0;
				yytext[yyleng-1]='\0';
				yytext++;
				return(atoi(yytext));
				}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 94 "decode.lex"
{
					yylval.flag=MEM_DIR_REG;
					yytext++;
					get_lexdata(yytext,tempbuf);	//Not at all tested. Vulnerable ***
					yylval.flag2=atoi(tempbuf);
					return(atoi(yytext));					
					}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 101 "decode.lex"
{
					yylval.flag=MEM_DIR_REG;
					yytext++;
					get_lexdata(yytext,tempbuf);	//Not at all tested. Vulnerable ***
					yylval.flag2=atoi(tempbuf) + T0;
					return(atoi(yytext));					
					}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 108 "decode.lex"
{
					yylval.flag=MEM_DIR_SP;
					yytext++;
					get_lexdata(yytext,tempbuf);	//Not at all tested. Vulnerable ***
					yylval.flag2=SP_REG;
					return(atoi(yytext));					
					}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 115 "decode.lex"
{
					yylval.flag=MEM_DIR_BP;
					yytext++;
					get_lexdata(yytext,tempbuf);	//Not at all tested. Vulnerable ***
					yylval.flag2=BP_REG;
					return(atoi(yytext));					
					}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 122 "decode.lex"
{
					yylval.flag=MEM_DIR_IP;
					yytext++;
					get_lexdata(yytext,tempbuf);	//Not at all tested. Vulnerable ***
					yylval.flag2=IP_REG;
					return(atoi(yytext));					
					}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 129 "decode.lex"
{
					yylval.flag=MEM_DIR_PTBR;
					yytext++;
					get_lexdata(yytext,tempbuf);	//Not at all tested. Vulnerable ***
					yylval.flag2=PTBR_REG;
					return(atoi(yytext));					
					}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 136 "decode.lex"
{
					yylval.flag=MEM_DIR_PTLR;
					yytext++;
					get_lexdata(yytext,tempbuf);	//Not at all tested. Vulnerable ***
					yylval.flag2=PTLR_REG;
					return(atoi(yytext));					
					}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 143 "decode.lex"
{
					yylval.flag=MEM_DIR_EFR;
					yytext++;
					get_lexdata(yytext,tempbuf);	//Not at all tested. Vulnerable ***
					yylval.flag2=EFR_REG;
					return(atoi(yytext));					
					}					
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 150 "decode.lex"
{
					yylval.flag=MEM_DIR_IN;
					yytext++;
					get_lexdata(yytext,tempbuf);	//Not at all tested. Vulnerable ***
					yylval.flag2=atoi(tempbuf);
					return(atoi(yytext));					
					}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 159 "decode.lex"
; 
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 160 "decode.lex"
{ //printf("<ERROR> HALT instruction missing\n"); 
					printf("OVER!!!!!!!!\n"); 
					yylval.flag=0; yylval.flag2=0; return(HALT);
					}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 164 "decode.lex"
{ strcpy(yylval.data,yytext); yylval.flag=0; yylval.flag2=0; return(LABEL);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 165 "decode.lex"
{
						yytext[yyleng-1]='\0';
						yytext++;
						strcpy(yylval.data,yytext);
						yylval.flag=0; yylval.flag2=0;
						return(STRING);
					}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 172 "decode.lex"
;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 173 "decode.lex"
;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 174 "decode.lex"
;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 175 "decode.lex"
;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 176 "decode.lex"
{ printf("<ERROR:%d: Unexpected symbol %s\n",getInteger(reg[IP_REG]),yytext);
					  exit(0);
					}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 179 "decode.lex"
ECHO;
	YY_BREAK
#line 1384 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 176 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 176 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 175);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 179 "decode.lex"


void get_lexdata(char buf1[],char buf2[]) 			//Not at all tested. Vulnerable ***
{
	int i,flag,j;
	for(i=0,j=0,flag=0;buf1[i]!='\0';i++,j++)
	{
		if(buf1[i] == ']')
		{
			flag = 1;
			j=0;
			buf1[i]='\0';
			if(buf1[i+1] == 'R' || buf1[i+1] == 'T')
			{
				i++;
				buf1[i]='\0';
			}			
		}
		if(flag == 1)
			buf2[j] = buf1[i];
	}
	buf2[j]='\0';	
}

